# Generated by Django 3.2.7 on 2021-10-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='free_collectible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
