# Generated by Django 3.2.7 on 2021-10-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribe_email',
            field=models.EmailField(max_length=100),
        ),
    ]
